server.port=18080
server.error.whitelabel.enabled=false

spring.application.name=TrodApplication
spring.datasource.url=jdbc:mariadb://localhost:3306/trod_database
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

mybatis.mapper-locations=classpath:mapper/*.xml

jwt.secret=your-very-secure-and-long-key-for-jwt-generation
# 1 day in milliseconds (1000*60*60*24)
jwt.expiration-time=86400000
jwt.key-name=trod_jwt